import { ImagePlus, RotateCcw, Trash2 } from "lucide-react";
import { MAX_LOGO_BYTES, QR_PRESETS } from "../constants/qrPresets";
import { SelectField, ToggleField } from "./forms/FormField";
function ColorControl({ id, label, value, onChange }) {
    return <label className="qr-color-control" htmlFor={id}><span>{label}</span><span><input id={id} onChange={(event) => onChange(event.target.value)} type="color" value={value}/><code>{value}</code></span></label>;
}
export default function QRStylePanel({ logo, onLogoChange, onReset, onStyleChange, style, showToast }) {
    const handleLogo = (file) => {
        if (!file)
            return;
        const allowed = ["image/png", "image/jpeg", "image/webp", "image/svg+xml"];
        if (!allowed.includes(file.type)) {
            showToast("Logo phải là PNG, JPG, SVG hoặc WEBP.", "error");
            return;
        }
        if (file.size > MAX_LOGO_BYTES) {
            showToast("Logo không được vượt quá 2 MB.", "error");
            return;
        }
        const reader = new FileReader();
        reader.onerror = () => showToast("Không thể đọc logo này.", "error");
        reader.onload = () => { onLogoChange(String(reader.result)); onStyleChange({ errorCorrectionLevel: "H" }); showToast("Đã thêm logo. Error correction được đặt thành H."); };
        reader.readAsDataURL(file);
    };
    return (<details className="qr-style-panel" id="qr-style-panel" open>
            <summary><span>Tùy chỉnh phong cách</span><small>Cập nhật theo thời gian thực</small></summary>
            <div className="qr-style-panel__body">
                <section><div className="qr-section-heading"><h3>Preset</h3><button className="qr-text-button" onClick={onReset} type="button"><RotateCcw aria-hidden="true" size={14}/> Reset</button></div><div className="qr-preset-grid">{QR_PRESETS.map((preset) => <button key={preset.id} onClick={() => onStyleChange(preset.style)} type="button">{preset.label}</button>)}</div></section>
                <section><h3>Màu sắc</h3><div className="qr-color-grid"><ColorControl id="qr-foreground" label="Màu QR" onChange={(foreground) => onStyleChange({ foreground })} value={style.foreground}/><ColorControl id="qr-background" label="Màu nền" onChange={(background) => onStyleChange({ background })} value={style.background}/></div><ToggleField checked={style.transparent} id="qr-transparent" onChange={(transparent) => onStyleChange({ transparent })}>Nền trong suốt</ToggleField><ToggleField checked={style.gradientEnabled} id="qr-gradient" onChange={(gradientEnabled) => onStyleChange({ gradientEnabled })}>Dùng gradient cho QR</ToggleField>{style.gradientEnabled ? <><div className="qr-form-grid"><SelectField id="qr-gradient-type" label="Loại gradient" onChange={(event) => onStyleChange({ gradientType: event.target.value })} value={style.gradientType}><option value="linear">Linear</option><option value="radial">Radial</option></SelectField><label className="qr-field" htmlFor="qr-gradient-angle"><span>Góc: {style.gradientRotation}°</span><input id="qr-gradient-angle" max="360" min="0" onChange={(event) => onStyleChange({ gradientRotation: Number(event.target.value) })} type="range" value={style.gradientRotation}/></label></div><div className="qr-color-grid"><ColorControl id="qr-gradient-start" label="Màu đầu" onChange={(gradientStart) => onStyleChange({ gradientStart })} value={style.gradientStart}/><ColorControl id="qr-gradient-end" label="Màu cuối" onChange={(gradientEnd) => onStyleChange({ gradientEnd })} value={style.gradientEnd}/></div></> : null}</section>
                <section><h3>Chấm và góc</h3><div className="qr-form-grid"><SelectField id="qr-dot-type" label="Kiểu chấm" onChange={(event) => onStyleChange({ dotType: event.target.value })} value={style.dotType}>{["square", "rounded", "dots", "classy", "classy-rounded", "extra-rounded"].map((value) => <option key={value} value={value}>{value}</option>)}</SelectField><SelectField id="qr-corner-square" label="Khung góc" onChange={(event) => onStyleChange({ cornerSquareType: event.target.value })} value={style.cornerSquareType}>{["square", "dot", "extra-rounded", "rounded", "classy", "classy-rounded"].map((value) => <option key={value} value={value}>{value}</option>)}</SelectField><SelectField id="qr-corner-dot" label="Chấm góc" onChange={(event) => onStyleChange({ cornerDotType: event.target.value })} value={style.cornerDotType}>{["square", "dot", "rounded", "dots", "classy", "classy-rounded"].map((value) => <option key={value} value={value}>{value}</option>)}</SelectField></div><div className="qr-color-grid"><ColorControl id="qr-corner-square-color" label="Màu khung góc" onChange={(cornerSquareColor) => onStyleChange({ cornerSquareColor })} value={style.cornerSquareColor}/><ColorControl id="qr-corner-dot-color" label="Màu chấm góc" onChange={(cornerDotColor) => onStyleChange({ cornerDotColor })} value={style.cornerDotColor}/></div></section>
                <section><h3>Logo</h3>{logo ? <div className="qr-logo-preview"><img alt="Logo QR" src={logo}/><button aria-label="Xóa logo" className="qr-icon-button" onClick={() => onLogoChange(null)} type="button"><Trash2 aria-hidden="true" size={16}/></button></div> : <label className="qr-logo-upload"><ImagePlus aria-hidden="true" size={20}/><span>Chọn logo<small>PNG, JPG, SVG, WEBP · tối đa 2 MB</small></span><input accept=".png,.jpg,.jpeg,.svg,.webp,image/png,image/jpeg,image/svg+xml,image/webp" onChange={(event) => handleLogo(event.target.files?.[0])} type="file"/></label>}<label className="qr-field" htmlFor="qr-logo-size"><span>Kích thước logo: {Math.round(style.logoSize * 100)}%</span><input disabled={!logo} id="qr-logo-size" max="0.45" min="0.15" onChange={(event) => onStyleChange({ logoSize: Number(event.target.value) })} step="0.01" type="range" value={style.logoSize}/></label><label className="qr-field" htmlFor="qr-logo-margin"><span>Khoảng quanh logo: {style.logoMargin}px</span><input disabled={!logo} id="qr-logo-margin" max="24" min="0" onChange={(event) => onStyleChange({ logoMargin: Number(event.target.value) })} type="range" value={style.logoMargin}/></label><ToggleField checked={style.logoBackground} id="qr-logo-background" onChange={(logoBackground) => onStyleChange({ logoBackground })}>Tạo vùng trống phía sau logo</ToggleField></section>
                <section><h3>Kích thước và độ bền</h3><div className="qr-form-grid"><label className="qr-field" htmlFor="qr-width"><span>Chiều rộng: {style.width}px</span><input id="qr-width" max="600" min="220" onChange={(event) => onStyleChange({ width: Number(event.target.value) })} step="10" type="range" value={style.width}/></label><label className="qr-field" htmlFor="qr-height"><span>Chiều cao: {style.height}px</span><input id="qr-height" max="600" min="220" onChange={(event) => onStyleChange({ height: Number(event.target.value) })} step="10" type="range" value={style.height}/></label><label className="qr-field" htmlFor="qr-margin"><span>Margin: {style.margin}px</span><input id="qr-margin" max="40" min="0" onChange={(event) => onStyleChange({ margin: Number(event.target.value) })} type="range" value={style.margin}/></label><SelectField id="qr-error-level" label="Error correction" onChange={(event) => onStyleChange({ errorCorrectionLevel: event.target.value })} value={logo ? "H" : style.errorCorrectionLevel}>{["L", "M", "Q", "H"].map((value) => <option key={value}>{value}</option>)}</SelectField></div>{logo ? <p className="qr-inline-note">Logo đang bật, mức H được dùng để tăng khả năng quét.</p> : null}</section>
            </div>
        </details>);
}
