import {
    ArrowUpIcon,
    BankIcon,
    BillIcon,
    BudgetIcon,
    CalendarIcon,
    BusinessIcon,
    CardIcon,
    CashIcon,
    CharityIcon,
    CoffeeIcon,
    CoinsIcon,
    DigitalWalletIcon,
    EducationIcon,
    EntertainmentIcon,
    EyeIcon,
    FamilyIcon,
    FinanceIcon,
    FoodIcon,
    FuelIcon,
    GiftIcon,
    HealthIcon,
    HomeIcon,
    MoreIcon,
    MovieIcon,
    PersonalCareIcon,
    PetIcon,
    RefundIcon,
    ReportIcon,
    BellIcon,
    SettingsIcon,
    ShoppingIcon,
    SubscriptionIcon,
    TagIcon,
    TaxIcon,
    TransactionListIcon,
    TransportIcon,
    TravelIcon,
    WalletIcon,
    WorkIcon,
    SwapIcon,
    ArrowDownIcon,
    ThemeIcon,
    PlusIcon,
    XIcon,
    EditIcon,
    TrashIcon,
    SearchIcon,
    SortIcon,
    GreetingIcon,
    TipIcon,
    FilterIcon,
    LogoutIcon,
    DownloadIcon,
    StarIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
} from "./BaseIcons";

export const baseIconSet = Object.freeze({
    bank: BankIcon,
    bills: BillIcon,
    budget: BudgetIcon,
    business: BusinessIcon,
    calendar: CalendarIcon,
    card: CardIcon,
    cash: CashIcon,
    category: TagIcon,
    charity: CharityIcon,
    chart: ReportIcon,
    coffee: CoffeeIcon,
    "digital-wallet": DigitalWalletIcon,
    education: EducationIcon,
    entertainment: EntertainmentIcon,
    eye: EyeIcon,
    family: FamilyIcon,
    finance: FinanceIcon,
    food: FoodIcon,
    fuel: FuelIcon,
    gifts: GiftIcon,
    health: HealthIcon,
    home: HomeIcon,
    income: ArrowUpIcon,
    more: MoreIcon,
    movie: MovieIcon,
    "personal-care": PersonalCareIcon,
    pets: PetIcon,
    refund: RefundIcon,
    saving: CoinsIcon,
    settings: SettingsIcon,
    shopping: ShoppingIcon,
    subscription: SubscriptionIcon,
    tax: TaxIcon,
    transactions: TransactionListIcon,
    "trend-down": ArrowDownIcon,
    "trend-up": ArrowUpIcon,
    transfer: SwapIcon,
    transport: TransportIcon,
    travel: TravelIcon,
    wallet: WalletIcon,
    work: WorkIcon,
    theme: ThemeIcon,
    notifications: BellIcon,
    app: DigitalWalletIcon,
    add: PlusIcon,
    close: XIcon,
    delete: TrashIcon,
    download: DownloadIcon,
    edit: EditIcon,
    favorite: StarIcon,
    filter: FilterIcon,
    logout: LogoutIcon,
    search: SearchIcon,
    sort: SortIcon,
    greeting: GreetingIcon,
    tip: TipIcon,
    visibility: EyeIcon,
    "chevron-down": ChevronDownIcon,
    "chevron-left": ChevronLeftIcon,
    "chevron-right": ChevronRightIcon,
    "chevron-up": ChevronUpIcon,
});
