export const hubModules = [
    {
        accent: "#2f7a4d",
        description: "Theo dõi thu chi, ví, ngân sách và báo cáo tài chính cá nhân.",
        eyebrow: "Tài chính",
        icon: "expenses",
        id: "expenses",
        path: "/expenses/dashboard",
        title: "Expenses",
    },
    {
        accent: "#8062a6",
        description: "Một câu nói, một khung cảnh và vài giây để lòng mình chậm lại.",
        eyebrow: "Cảm hứng",
        icon: "quotes",
        id: "quotes",
        path: "/quotes",
        title: "Lặng",
    },
    {
        accent: "#2f7181",
        description: "Cắt video hoặc tách âm thanh trực tiếp trên thiết bị.",
        eyebrow: "Media",
        icon: "media-cutter",
        id: "media-cutter",
        path: "/tools/media-cutter",
        title: "Tách và cắt âm thanh",
    },
    {
        accent: "#35498b",
        description: "Định dạng, thu gọn, kiểm tra và so sánh JSON ngay trong trình duyệt.",
        eyebrow: "Developer tools",
        icon: "json-toolkit",
        id: "json-toolkit",
        path: "/tools/json",
        title: "JSON Toolkit",
    },
    {
        accent: "#0f766e",
        description: "Tạo, tùy chỉnh, tải xuống và quét QR Code hoàn toàn trên thiết bị.",
        eyebrow: "Browser tools",
        icon: "qr-toolkit",
        id: "qr-toolkit",
        path: "/tools/qr",
        title: "QR Code Toolkit",
    },
    {
        accent: "#2563eb",
        description: "Thiết kế, chỉnh sửa và xuất CV chuyên nghiệp ngay trong trình duyệt.",
        eyebrow: "Sự nghiệp",
        icon: "cv-studio",
        id: "cv-studio",
        path: "/cv-studio",
        title: "CV Studio",
    },
];
